**Task:**

To write a Python program that:
*   Creates a 4 × 5 matrix representing a classroom seating arrangement.
*   Accepts 1 if a seat is occupied and 0 if a seat is empty.
*   Displays the seating arrangement.
*   Finds the total number of occupied seats.
*   Finds the total number of empty seats.

In [1]:
#Imports the NumPy library and gives it the shorter name np.
import numpy as np

#Creates an empty list to store the seating arrangement.
seats = []

In [2]:
#Repeats the loop for 4 rows.
for i in range(4):

    #Creates an empty list to store seats in the current row.
    row = []

    #Repeats the loop for 5 seats in each row.
    for j in range(5):

        #Takes 1 for an occupied seat or 0 for an empty seat.
        value = int(input(
            "Enter 1 for occupied, 0 for empty - Row " +
            str(i + 1) + ", Seat " + str(j + 1) + ": "
        ))

        #Adds the seat value to the current row.
        row.append(value)

    #Adds the completed row to the seating arrangement.
    seats.append(row)

Enter 1 for occupied, 0 for empty - Row 1, Seat 1: 1
Enter 1 for occupied, 0 for empty - Row 1, Seat 2: 0
Enter 1 for occupied, 0 for empty - Row 1, Seat 3: 1
Enter 1 for occupied, 0 for empty - Row 1, Seat 4: 1
Enter 1 for occupied, 0 for empty - Row 1, Seat 5: 0
Enter 1 for occupied, 0 for empty - Row 2, Seat 1: 0
Enter 1 for occupied, 0 for empty - Row 2, Seat 2: 0
Enter 1 for occupied, 0 for empty - Row 2, Seat 3: 1
Enter 1 for occupied, 0 for empty - Row 2, Seat 4: 1
Enter 1 for occupied, 0 for empty - Row 2, Seat 5: 0
Enter 1 for occupied, 0 for empty - Row 3, Seat 1: 0
Enter 1 for occupied, 0 for empty - Row 3, Seat 2: 1
Enter 1 for occupied, 0 for empty - Row 3, Seat 3: 0
Enter 1 for occupied, 0 for empty - Row 3, Seat 4: 1
Enter 1 for occupied, 0 for empty - Row 3, Seat 5: 0
Enter 1 for occupied, 0 for empty - Row 4, Seat 1: 1
Enter 1 for occupied, 0 for empty - Row 4, Seat 2: 0
Enter 1 for occupied, 0 for empty - Row 4, Seat 3: 0
Enter 1 for occupied, 0 for empty - Row 4, Sea

In [3]:
#Converts the list into a 4 × 5 NumPy array.
seats = np.array(seats)

In [4]:
#Displays the heading for the seating arrangement.
print("Seating Arrangement:")

#Displays the 4 × 5 seating matrix.
print(seats)

#Calculates and displays the total number of occupied seats.
print("Occupied Seats:", np.sum(seats))

#Counts and displays the total number of empty seats.
print("Empty Seats:", np.sum(seats == 0))

Seating Arrangement:
[[1 0 1 1 0]
 [0 0 1 1 0]
 [0 1 0 1 0]
 [1 0 0 1 1]]
Occupied Seats: 10
Empty Seats: 10
