In [1]:
#Enter marks of 5 students in 3 subjects and find the student who scored the highest in each subject.

import numpy as np

marks = []

for i in range(5):
    row = []

    for j in range(3):
        mark = int(input(
            "Enter marks of student " + str(i + 1) +
            " in subject " + str(j + 1) + ": "
        ))
        row.append(mark)

    marks.append(row)

marks = np.array(marks)

best_students = np.argmax(marks, axis=0)

print("Marks:")
print(marks)

print("Best student in Subject 1:", best_students[0] + 1)
print("Best student in Subject 2:", best_students[1] + 1)
print("Best student in Subject 3:", best_students[2] + 1)

Enter marks of student 1 in subject 1: 100
Enter marks of student 1 in subject 2: 90
Enter marks of student 1 in subject 3: 80
Enter marks of student 2 in subject 1: 10
Enter marks of student 2 in subject 2: 20
Enter marks of student 2 in subject 3: 100
Enter marks of student 3 in subject 1: 40
Enter marks of student 3 in subject 2: 67
Enter marks of student 3 in subject 3: 99
Enter marks of student 4 in subject 1: 33
Enter marks of student 4 in subject 2: 87
Enter marks of student 4 in subject 3: 97
Enter marks of student 5 in subject 1: 65
Enter marks of student 5 in subject 2: 64
Enter marks of student 5 in subject 3: 34
Marks:
[[100  90  80]
 [ 10  20 100]
 [ 40  67  99]
 [ 33  87  97]
 [ 65  64  34]]
Best student in Subject 1: 1
Best student in Subject 2: 1
Best student in Subject 3: 2
