**Task:**

To write a Python program that:
*   Accepts marks of 5 students in 3 subjects.
*   Stores the marks in a NumPy array.
*   Finds the student who scored the highest marks in each subject.
*   Displays the marks and the best student for each subject.

In [1]:
#Imports the NumPy library and gives it the shorter name np.
import numpy as np

#Creates an empty list to store the marks.
marks = []

In [2]:
#Repeats the loop for 5 students.
for i in range(5):

    #Creates an empty list to store marks for the current student.
    row = []

    #Repeats the loop for 3 subjects.
    for j in range(3):

        #Takes the marks of a student in a subject.
        mark = int(input(
            "Enter marks of student " + str(i + 1) +
            " in subject " + str(j + 1) + ": "
        ))

        #Adds the mark to the current student's row.
        row.append(mark)

    #Adds the completed row to the marks list.
    marks.append(row)

Enter marks of student 1 in subject 1: 100
Enter marks of student 1 in subject 2: 2
Enter marks of student 1 in subject 3: 87
Enter marks of student 2 in subject 1: 23
Enter marks of student 2 in subject 2: 0
Enter marks of student 2 in subject 3: 96
Enter marks of student 3 in subject 1: 34
Enter marks of student 3 in subject 2: 55
Enter marks of student 3 in subject 3: 87
Enter marks of student 4 in subject 1: 57
Enter marks of student 4 in subject 2: 35
Enter marks of student 4 in subject 3: 99
Enter marks of student 5 in subject 1: 17
Enter marks of student 5 in subject 2: 81
Enter marks of student 5 in subject 3: 64


In [3]:
#Converts the list into a 5 × 3 NumPy array.
marks = np.array(marks)

#Finds the student with the highest marks in each subject.
best_students = np.argmax(marks, axis=0)

In [4]:
#Displays the heading for the marks.
print("Marks:")

#Displays the marks of all 5 students.
print(marks)

#Displays the student number with the highest marks in Subject 1.
print("Best student in Subject 1:", best_students[0] + 1)

#Displays the student number with the highest marks in Subject 2.
print("Best student in Subject 2:", best_students[1] + 1)

#Displays the student number with the highest marks in Subject 3.
print("Best student in Subject 3:", best_students[2] + 1)

Marks:
[[100   2  87]
 [ 23   0  96]
 [ 34  55  87]
 [ 57  35  99]
 [ 17  81  64]]
Best student in Subject 1: 1
Best student in Subject 2: 5
Best student in Subject 3: 4
