In [1]:
#Enter a 4 × 4 matrix and display only its border elements.

import numpy as np

matrix = []

for i in range(4):
    row = []
    for j in range(4):
        value = int(input("Enter value: "))
        row.append(value)
    matrix.append(row)

matrix = np.array(matrix)

print("Matrix:")
print(matrix)

print("Top Row:", matrix[0])
print("Bottom Row:", matrix[-1])
print("Left Column:", matrix[:, 0])
print("Right Column:", matrix[:, -1])

Enter value: 12
Enter value: 23
Enter value: 45
Enter value: 6
Enter value: 7
Enter value: 100
Enter value: 23
Enter value: 89
Enter value: 0
Enter value: 1
Enter value: 90
Enter value: 98
Enter value: 12
Enter value: 26
Enter value: 93
Enter value: 54
Matrix:
[[ 12  23  45   6]
 [  7 100  23  89]
 [  0   1  90  98]
 [ 12  26  93  54]]
Top Row: [12 23 45  6]
Bottom Row: [12 26 93 54]
Left Column: [12  7  0 12]
Right Column: [ 6 89 98 54]
