**Task**

To write a Python program that:
*   Accepts values for a 4 × 4 matrix.
*   Stores the values in a NumPy array.
*   Displays the complete matrix.
*   Extracts and displays only the border elements of the matrix.
*   Displays the top row, bottom row, left column, and right column separately.

In [1]:
#Imports the NumPy library and gives it the shorter name np.
import numpy as np

#Creates an empty list to store the matrix.
matrix = []

In [2]:
#Repeats the loop for 4 rows.
for i in range(4):

    #Creates an empty list to store values in the current row.
    row = []

    #Repeats the loop for 4 columns.
    for j in range(4):

        #Takes an integer value from the user.
        value = int(input("Enter value: "))

        #Adds the value to the current row.
        row.append(value)

    #Adds the completed row to the matrix.
    matrix.append(row)

Enter value: 2
Enter value: 4
Enter value: 6
Enter value: 8
Enter value: 10
Enter value: 12
Enter value: 14
Enter value: 16
Enter value: 18
Enter value: 20
Enter value: 22
Enter value: 24
Enter value: 25
Enter value: 26
Enter value: 34
Enter value: 67


In [3]:
#Converts the list into a 4 × 4 NumPy array.
matrix = np.array(matrix)

In [4]:
#Displays the heading for the matrix.
print("Matrix:")

#Displays the 4 × 4 matrix.
print(matrix)

#Displays the top row of the matrix.
print("Top Row:", matrix[0])

#Displays the bottom row of the matrix.
print("Bottom Row:", matrix[-1])

#Displays the left column of the matrix.
print("Left Column:", matrix[:, 0])

#Displays the right column of the matrix.
print("Right Column:", matrix[:, -1])

Matrix:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [25 26 34 67]]
Top Row: [2 4 6 8]
Bottom Row: [25 26 34 67]
Left Column: [ 2 10 18 25]
Right Column: [ 8 16 24 67]
